In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam

# Multi-layered RNNs

In [2]:
batch_size=4
seq_len=10
input_size=20
inp = torch.randn((4, 10, 20))

In [3]:
hidden_size=25
num_layers=2
model = nn.RNN(input_size, hidden_size, num_layers=num_layers, batch_first=True)

In [4]:
h_0 = torch.zeros(num_layers, batch_size, hidden_size)

In [5]:
all_outputs, last_hidden = model(inp, h_0)

In [6]:
all_outputs.shape, last_hidden.shape

(torch.Size([4, 10, 25]), torch.Size([2, 4, 25]))

In [7]:
# all_outputs -> batch_size x seq_len x hidden_size || last layer hidden_state corresponsing to each element in the sequence
# last_hidden -> layers x batch x hidden_size || The last hidden_state corresponding to each layer for each element in batch

In [8]:
all_outputs[0,-1,:] 

tensor([-0.1657,  0.7161,  0.3196,  0.0070, -0.0670, -0.5448,  0.3985, -0.4826,
        -0.2479,  0.1314,  0.5026,  0.4780, -0.0098, -0.1489, -0.1841,  0.2799,
         0.1832, -0.3853,  0.0462,  0.1440,  0.2423, -0.4685,  0.1583,  0.1670,
         0.0807], grad_fn=<SliceBackward0>)

In [9]:
last_hidden[1,0,:]

tensor([-0.1657,  0.7161,  0.3196,  0.0070, -0.0670, -0.5448,  0.3985, -0.4826,
        -0.2479,  0.1314,  0.5026,  0.4780, -0.0098, -0.1489, -0.1841,  0.2799,
         0.1832, -0.3853,  0.0462,  0.1440,  0.2423, -0.4685,  0.1583,  0.1670,
         0.0807], grad_fn=<SliceBackward0>)

# Bidirectional RNNs

In [10]:
#batch_size=4
#seq_len=10
#input_size=20
#hidden_size=25 
num_layers=1
model = nn.RNN(input_size, hidden_size, num_layers=num_layers, bidirectional=True, batch_first=True)

In [11]:
h_0 = torch.zeros(2*num_layers, batch_size, hidden_size)

In [12]:
all_outputs, last_hidden = model(inp, h_0)

In [13]:
all_outputs.shape, last_hidden.shape

(torch.Size([4, 10, 50]), torch.Size([2, 4, 25]))

In [14]:
# all_outputs -> batch_size x seq_len x last_hidden*2 || concatenated hidden states for each direction
# last_hidden -> 2*layers x batch_size x last_hidden

In [15]:
all_outputs[0, -1, :25]

tensor([ 0.0325,  0.4100,  0.4651, -0.5051, -0.0025,  0.4226,  0.1724, -0.5556,
        -0.3997,  0.5951,  0.1455,  0.2211,  0.2792, -0.6356, -0.2430,  0.4743,
         0.1947, -0.7521,  0.7745, -0.1530,  0.4593, -0.3852, -0.9220,  0.4367,
        -0.1444], grad_fn=<SliceBackward0>)

In [16]:
last_hidden[0, 0, :]

tensor([ 0.0325,  0.4100,  0.4651, -0.5051, -0.0025,  0.4226,  0.1724, -0.5556,
        -0.3997,  0.5951,  0.1455,  0.2211,  0.2792, -0.6356, -0.2430,  0.4743,
         0.1947, -0.7521,  0.7745, -0.1530,  0.4593, -0.3852, -0.9220,  0.4367,
        -0.1444], grad_fn=<SliceBackward0>)

In [17]:
all_outputs[0, 0, 25:]

tensor([-0.1558,  0.4311,  0.3527, -0.6202,  0.4133, -0.2571,  0.7671,  0.5944,
         0.4666, -0.7220, -0.6334, -0.2734, -0.0318,  0.2264,  0.3078,  0.2369,
         0.2561,  0.1723,  0.6998, -0.9119, -0.3580,  0.4926,  0.6914, -0.4143,
         0.4746], grad_fn=<SliceBackward0>)

In [18]:
last_hidden[1, 0, :]

tensor([-0.1558,  0.4311,  0.3527, -0.6202,  0.4133, -0.2571,  0.7671,  0.5944,
         0.4666, -0.7220, -0.6334, -0.2734, -0.0318,  0.2264,  0.3078,  0.2369,
         0.2561,  0.1723,  0.6998, -0.9119, -0.3580,  0.4926,  0.6914, -0.4143,
         0.4746], grad_fn=<SliceBackward0>)

In [19]:
# with multiple layers..

In [20]:
#batch_size=4
#seq_len=10
#input_size=20
#hidden_size=25
num_layers=2
model = nn.RNN(input_size, hidden_size, num_layers=num_layers, bidirectional=True, batch_first=True)

In [21]:
h_0 = torch.zeros(2*num_layers, batch_size, hidden_size)

In [22]:
all_outputs, last_hidden = model(inp, h_0)

In [23]:
all_outputs.shape, last_hidden.shape

(torch.Size([4, 10, 50]), torch.Size([4, 4, 25]))

In [24]:
# all_outputs -> batch_size x seq_len x last_hidden*2 || concatenated hidden states for each direction
# last_hidden -> 2*layers x batch_size x last_hidden

In [25]:
all_outputs[0, -1, :25]

tensor([ 0.2758,  0.3133, -0.3730, -0.2417,  0.5501,  0.3840, -0.1611, -0.6043,
        -0.1783, -0.1369, -0.5605, -0.7705, -0.6021,  0.3855, -0.0139, -0.5534,
         0.1843,  0.2959,  0.1496, -0.5904, -0.0516,  0.3631,  0.2536, -0.2494,
        -0.3859], grad_fn=<SliceBackward0>)

In [26]:
last_hidden[2, 0, :]

tensor([ 0.2758,  0.3133, -0.3730, -0.2417,  0.5501,  0.3840, -0.1611, -0.6043,
        -0.1783, -0.1369, -0.5605, -0.7705, -0.6021,  0.3855, -0.0139, -0.5534,
         0.1843,  0.2959,  0.1496, -0.5904, -0.0516,  0.3631,  0.2536, -0.2494,
        -0.3859], grad_fn=<SliceBackward0>)

In [27]:
all_outputs[0, 0, 25:]

tensor([ 0.5809, -0.4013,  0.1733, -0.3643,  0.7126, -0.3957,  0.2753, -0.1700,
        -0.6931,  0.5427,  0.1374, -0.7075, -0.0496,  0.6920,  0.1789, -0.5429,
        -0.8129, -0.2852, -0.7869, -0.1182, -0.2218, -0.5136, -0.2260, -0.1367,
         0.2906], grad_fn=<SliceBackward0>)

In [28]:
last_hidden[3, 0, :]

tensor([ 0.5809, -0.4013,  0.1733, -0.3643,  0.7126, -0.3957,  0.2753, -0.1700,
        -0.6931,  0.5427,  0.1374, -0.7075, -0.0496,  0.6920,  0.1789, -0.5429,
        -0.8129, -0.2852, -0.7869, -0.1182, -0.2218, -0.5136, -0.2260, -0.1367,
         0.2906], grad_fn=<SliceBackward0>)

# LSTM

In [29]:
# For LSTM, you would require definig an additional initial cell state c_0 (like h_0)

In [30]:
rnn = nn.LSTM(input_size=10, hidden_size=20, batch_first=True)
input = torch.randn(3, 5, 10) # batch_size x seq_len x embedding
h0 = torch.randn(1, 3, 20) # layers x batch_size x hidden_size
c0 = torch.randn(1, 3, 20) # layers x batch_size x hidden_size
output, (hn, cn) = rnn(input, (h0, c0))

In [31]:
output.shape # batch_size x seq_len x hidden_size || hidden states corresponding to each element in the sequence

torch.Size([3, 5, 20])

In [32]:
hn.shape # last hidden state || layers x batch x hidden_size

torch.Size([1, 3, 20])

In [33]:
# cn.shape # last cell state || layers x batch x hidden_size 

In [34]:
output[0,-1,:]

tensor([ 0.0349, -0.0249,  0.0193, -0.0514, -0.1435, -0.0680, -0.0344,  0.2321,
         0.0605,  0.2768, -0.1474, -0.0712,  0.0795, -0.1843, -0.0260,  0.1664,
        -0.1067, -0.3437,  0.2659,  0.0719], grad_fn=<SliceBackward0>)

In [35]:
hn[0,0,:]

tensor([ 0.0349, -0.0249,  0.0193, -0.0514, -0.1435, -0.0680, -0.0344,  0.2321,
         0.0605,  0.2768, -0.1474, -0.0712,  0.0795, -0.1843, -0.0260,  0.1664,
        -0.1067, -0.3437,  0.2659,  0.0719], grad_fn=<SliceBackward0>)

# Task

Design a GRU model (utilize multiple layers and bidirectionality) for sentiment classification on the SST dataset. First create a dataset class for the SST dataset. Train your model on the training set. At the end of each epoch measure the validation accuracy and save the model with the best validation accuracy. Evaluate you model and print the accuracy on the test set